manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: hailee0710
      url-base: https://github.com/hailee0710
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-dongle-eyes
      remote: hailee0710
      revision: main
  self:
    path: config
